development:
  adapter: postgresql
  database: knowledgeable_development
test:
  adapter: postgresql
  database: knowledgeable_test
production:
  adapter: postgresql
  database: knowledgeable_production